name: tkpipeline CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: tereverde
          POSTGRES_USER: tereuser
          POSTGRES_PASSWORD: 1234
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U tereuser -d tereverde"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_NAME: tereverde
      DATABASE_USER: tereuser
      DATABASE_PASSWORD: 1234
      DATABASE_HOST: localhost
      DATABASE_PORT: 5432
      DEBUG: False
      SECRET_KEY: "fake-secret-key-for-ci"

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies
      working-directory: tereverde 
      run: |
        python -m venv faculdade
        source faculdade/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
        
    
    - name: Wait for PostgreSQL to be ready
      run: |
        until pg_isready -h localhost -p 5432 -U tereuser; do
          echo "‚è≥ Waiting for DB..."
          sleep 2
        done

    - name: Run migrations
      env:
        DATABASE_NAME: ${{ env.DATABASE_NAME }}
        DATABASE_USER: ${{ env.DATABASE_USER }}
        DATABASE_PASSWORD: ${{ env.DATABASE_PASSWORD }}
        DATABASE_HOST: ${{ env.DATABASE_HOST }}
        DATABASE_PORT: ${{ env.DATABASE_PORT }}
      run: |
        source faculdade/bin/activate
        python manage.py migrate

    - name: Run tests
      run: |
        source faculdade/bin/activate
        python manage.py test
